<?php

declare(strict_types=1);

namespace SoftwareFoundation\Kernel\Ports;

/**
 * Database abstraction port.
 *
 * Provides a host-agnostic interface for all relational persistence operations.
 * Implementations adapt to the concrete database driver available in the host
 * environment (e.g. PDO, WordPress $wpdb, Doctrine DBAL, etc.).
 *
 * Every query method accepts parameterised SQL to prevent injection.
 * The {@see tableName()} helper lets callers remain agnostic of any
 * host-specific table-prefix convention.
 */
interface PersistencePort
{
    /**
     * Execute a query and return all matching rows.
     *
     * @param string $sql    Parameterised SQL statement.
     * @param array  $params Positional or named bind values.
     *
     * @return array<int, array<string, mixed>> List of associative-array rows.
     */
    public function query(string $sql, array $params = []): array;

    /**
     * Execute a query and return the first row, or null when no rows match.
     *
     * @param string $sql    Parameterised SQL statement.
     * @param array  $params Positional or named bind values.
     *
     * @return array<string, mixed>|null Single associative-array row or null.
     */
    public function queryRow(string $sql, array $params = []): ?array;

    /**
     * Execute a query and return a single scalar value.
     *
     * Useful for COUNT, MAX, or any query that produces exactly one column/row.
     *
     * @param string $sql    Parameterised SQL statement.
     * @param array  $params Positional or named bind values.
     *
     * @return mixed The scalar value, or null when no result is found.
     */
    public function queryValue(string $sql, array $params = []): mixed;

    /**
     * Insert a row into the given table.
     *
     * @param string               $table Logical table name (without prefix).
     * @param array<string, mixed> $data  Column => value pairs to insert.
     *
     * @return int The last-insert ID generated by the database.
     */
    public function insert(string $table, array $data): int;

    /**
     * Update rows in the given table that match the where clause.
     *
     * @param string               $table Logical table name (without prefix).
     * @param array<string, mixed> $data  Column => value pairs to set.
     * @param array<string, mixed> $where Column => value equality conditions (AND-ed).
     *
     * @return int Number of affected rows.
     */
    public function update(string $table, array $data, array $where): int;

    /**
     * Delete rows from the given table that match the where clause.
     *
     * @param string               $table Logical table name (without prefix).
     * @param array<string, mixed> $where Column => value equality conditions (AND-ed).
     *
     * @return int Number of deleted rows.
     */
    public function delete(string $table, array $where): int;

    /**
     * Begin a database transaction.
     */
    public function beginTransaction(): void;

    /**
     * Commit the current transaction.
     */
    public function commit(): void;

    /**
     * Roll back the current transaction.
     */
    public function rollback(): void;

    /**
     * Execute the given callable inside a transaction.
     *
     * The transaction is committed when the callable returns normally and
     * rolled back if any Throwable is thrown. The callable's return value
     * is forwarded to the caller.
     *
     * @template T
     *
     * @param callable(): T $fn Business logic to execute transactionally.
     *
     * @return T
     */
    public function transactional(callable $fn): mixed;

    /**
     * Resolve the fully-qualified (prefixed) table name for the current host.
     *
     * @param string $base The logical/base table name (e.g. "bookings").
     *
     * @return string The prefixed table name ready for use in SQL (e.g. "wp_bkd_bookings").
     */
    public function tableName(string $base): string;
}
